# Generated by Django 3.2.4 on 2023-08-03 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "budget",
                    models.IntegerField(
                        default=1000000,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("slug", models.SlugField(default="")),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "Euro"),
                            ("RUB", "Rubles"),
                            ("USD", "Dollars"),
                        ],
                        default="R",
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
