# Generated by Django 3.2.5 on 2022-02-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_auto_20220222_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Rubles'), ('RUB', 'Dollars')], default='R', max_length=3),
        ),
    ]
