# Generated by Django 3.2.5 on 2022-02-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_alter_movie_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('RUB', 'Rubles'), ('USD', 'Dollars')], default='R', max_length=3),
        ),
    ]
